# Generated by Django 3.1.1 on 2020-09-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduacion_ojo_izquierdo', models.IntegerField()),
                ('graduacion_ojo_derecho', models.IntegerField()),
                ('edad_actual', models.IntegerField()),
                ('edad_empezo_lentes', models.IntegerField()),
                ('causa_uso_lentes', models.IntegerField(blank=True, choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')])),
            ],
        ),
    ]
