# Generated by Django 3.1.1 on 2020-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='causa_uso_lentes',
            field=models.IntegerField(blank=True, choices=[(1, 'Enfermedad'), (2, 'Accidente'), (3, 'Nacimiento'), (4, 'A causa de mi trabajo/otros')]),
        ),
    ]
