# Generated by Django 3.1.1 on 2020-09-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20200920_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuejaSugerencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queja_sugerencia', models.TextField()),
            ],
        ),
    ]
